<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }


    public function render($request, Throwable $e)
    {
        if ($e instanceof AuthorizationException) {
            return response()->json(['message' => 'This action is unauthorized.'], Response::HTTP_FORBIDDEN);
        } elseif ($e instanceof ModelNotFoundException) {
            return response()->json(['error' => 'The requested resource was not found.'], Response::HTTP_NOT_FOUND);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
